name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: docker build -t nishedcob/demo-static-app:ci .
    - name: Tag Docker Image
      run: |
        docker tag nishedcob/demo-static-app:ci nishedcob/demo-static-app:$GITHUB_SHA
        docker tag nishedcob/demo-static-app:ci nishedcob/demo-static-app:$(git rev-parse --short HEAD)
    - name: Push to Docker Hub
      run: |
        echo $DOCKER_HUB_ACCESS_TOKEN | docker login --username $DOCKER_HUB_USER
        docker push nishedcob/demo-static-app:$GITHUB_SHA
        docker push nishedcob/demo-static-app:$(git rev-parse --short HEAD)
      with:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
