name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commit
      uses: actions/checkout@v1
    - name: Install jq
      run: sudo apt install jq
    - name: Build index.html
      run: make index.html
    - name: Build Docker Image
      run: docker build -t nishedcob/demo-static-app:ci .
    - name: Tag Docker Image
      run: |
        docker tag nishedcob/demo-static-app:ci nishedcob/demo-static-app:$GITHUB_SHA
        docker tag nishedcob/demo-static-app:ci nishedcob/demo-static-app:$(git rev-parse --short HEAD)
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push to Docker Hub
      run: |
        docker push nishedcob/demo-static-app:$GITHUB_SHA
        docker push nishedcob/demo-static-app:$(git rev-parse --short HEAD)
