name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: docker build -t nishedcob/demo-static-app:ci .
    - name: Tag Docker Image
      run: |
        docker tag nishedcob/demo-static-app:ci nishedcob/demo-static-app:$GITHUB_SHA
        docker tag nishedcob/demo-static-app:ci nishedcob/demo-static-app:$(git rev-parse --short HEAD)
